feat(bin): handle nonexistent files in `del` script

diff --git a/bin/.bin/del b/bin/.bin/del
--- a/bin/.bin/del
+++ b/bin/.bin/del
@@ -14,8 +14,17 @@ fi
 
 files=()
 for file in "$@"; do
-  files+=("$(realpath "$file")")
+    if [ -e "$file" ]; then
+        files+=("$(realpath "$file")")
+    else
+        echo "del: file '$file' not found"
+    fi
 done
+
+if [ ${#files[@]} -eq 0 ]; then
+    echo "del: no valid files to delete"
+    exit 1
+fi
+
 formatted=$(printf "\",POSIX file \"%s" "${files[@]}")\"
 osascript -ss -e"tell app \"Finder\" to delete {${formatted:2}}" 1>/dev/null
-
